---
## tested on
# - ubuntu focal
# - debian bullseye

- name: Install quemu-guest-agent
  apt:
    name: qemu-guest-agent
    state: present
    update_cache: yes

- name: "Make sure quemu guest agent service is {{ qga_state }}"
  ansible.builtin.systemd:
    state: "{{ qga_state }}"
    name: qemu-guest-agent.service
  when: qga_service_status_ensure
