### dumps qemu copy on target system
# installs openwrt image on target's disk via dd
#
# This playbook needs to be running in installer livedistro as sysrescuecd
---
- hosts: all
  become: yes
  # gather_facts: no
  vars:
    root_part_number: 2
  tasks:
################################################################################
################### image copy to hard drive  ##################################
################################################################################
    # the image generation appends a signature which brokes the gzip file appending information gzip understand as trailing garbage
    # TODO: solution:
    #   curl | fwtool -T -i | zcat
    # https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=target/linux/x86/image/Makefile;hb=598b29585ed9501e751b8d3faf3b6e017ad96baa#l109
  - name: "curl -s {{ cloud_img_url }} | zcat | dd of={{ vm_disk }}"
    ansible.builtin.shell: "curl -s {{ cloud_img_url }} | zcat | dd of={{ vm_disk }}"
      ## command + curl is neccessary because url nor curl can get the url without body/content
    poll: 0
    async: 45000
    register: q_st

  - name: Check status of qemu task
    async_status:
      jid: "{{ q_st.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: "{{ wait_qemu_img | default(1800) }}"

  - name: sync
    ansible.builtin.command: "sync"
    poll: 0
    async: 45000
    register: s_st

  - name: Check status of sync task
    async_status:
      jid: "{{ s_st.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: "{{ wait_sync | default(1800) }}"

  - name: "growpart for {{ vm_disk }} {{ root_part_number }}"
    ansible.builtin.command: "growpart --fudge 1 {{ vm_disk }} {{ root_part_number}}"
    poll: 0
    async: 45000
    register: g_st

  - name: Check status of growpart task
    async_status:
      jid: "{{ g_st.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: "{{ wait_growpart | default(1800) }}"
