### setups proxmox settings for VM
# Cloud-Init setup
#
# This playbook may be running in installer livedistro as sysrescuecd
---
- hosts: all
  become: yes
  tasks:
  - name: Install proxmoxer pip package
    ansible.builtin.pip:
      # https://pypi.org/project/docker-compose/#history
      name: proxmoxer
      state: present
    become: yes
    ignore_errors: true
    register: install_proxmoxer

  - name: install dependency for pip
    ansible.builtin.command: pacman --noconfirm  -Sy python-setuptools
    when: install_proxmoxer is failed

  - name: Install proxmoxer pip package
    ansible.builtin.pip:
      # https://pypi.org/project/docker-compose/#history
      name: proxmoxer
      state: present
    become: yes
    when: install_proxmoxer is failed

  - name: Update cloud-init VM config
    community.general.proxmox_kvm:
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_token_id }}"
      api_token_secret: "{{ proxmox_token }}"
      api_host: "{{ proxmox_api_host }}"
      node: "{{ proxmox_node }}"
      vmid: "{{ vm_id }}"
      ciuser: "{{ cloud_init_user }}"
      cipassword: "{{ cloud_init_password }}"
      ipconfig:
        ipconfig0: "{{ cloud_init_ipconfig }}"
      sshkeys: "{{ cloud_init_ssh_keys }}"
      # proxmox_default_behavior: compatibility
      update: yes
